### ISSUE TITLE
Add theme selector

### ISSUE THREAD

**Issue by rejas** [Neofonie/tech-radar#15]
How can I select the dark theme? Isnt there a button anywhere for that?

**Comment by seekwhencer** [comment]
yes, you can... but: in chrome the css onload listener will not work correctly

**Comment by rejas** [comment]
would be cool to have it like this:
- step 1: per default the site uses the prefers-color-scheme media query to either display dark or light theme
- optional step 2: in the bottom right there is a button that toggles between all avaiable themes
- optional step 3: the current theme is saved locally for the next visit

**Comment by dutscher** [comment]
brauch ma net
