### ISSUE TITLE
Add eslint to project

### ISSUE THREAD

**Issue by rejas** [Neofonie/tech-radar#3]
Ziel:
- neues script in package.json welches eslint auf den js-dateien ausführt

TODO:
- eslint via npm im projekt als devDependency installieren
- eslint config aus bechtle-porjekt übernehmen
- script eintrag in package-json erstellen, der eslint auf den js-dateien ausführt
- die 100 warnungen lassen wir dann erstmal so wie sie sind :-)

Siehe auch:
https://confluence.neofonie.de/display/KB/Javascript+Styleguide
https://eslint.org/docs/user-guide/getting-started#local-installation-and-usage

**Comment by bitjoo** [comment]
@MadNewjean Thank you.
:heavy_check_mark: #4
